version: 2.1
# Use a package of configuration called an orb.
orbs:
jobs:
 configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["c9:83:3a:4f:9f:73:b7:2b:b0:94:70:61:fc:98:ae:ea"] 
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory.txt ~/tasks/main.yml

workflows:
  myWorkflow:
    jobs:
      - configure_infrastructure